apache:
  image: dockerizedrupal/apache-2.4:1.2.0
  hostname: apache
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - apache-data
  links:
    - php
apache-data:
  image: dockerizedrupal/apache-2.4:1.2.0
  hostname: apache-data
  entrypoint: ["/bin/echo", "Data-only container for Apache."]
  volumes:
    - .:/apache/data
php:
  image: dockerizedrupal/php-5.3:1.2.7
  hostname: php
  volumes_from:
    - apache-data
  environment:
    - SERVER_NAME=localhost
    - TIMEZONE=Etc/UTC
    - DRUPAL_VERSION=7
    - DRUSH_VERSION=7
    - SMTP_HOST=
    - SMTP_PORT=25
    - MYSQL_HOST=
    - MYSQL_PORT=3306
    - MEMCACHED_HOST=
    - MEMCACHED_PORT=11211
    - REDIS_HOST=
    - REDIS_PORT=6379
    - PHP_INI_REALPATH_CACHE_SIZE=256k
    - PHP_INI_REALPATH_CACHE_TTL=3600
    - PHP_INI_POST_MAX_SIZE=512M
    - PHP_INI_TIMEZONE=UTC
    - PHP_INI_UPLOAD_MAX_FILESIZE=512M
    - PHP_INI_SHORT_OPEN_TAG=On
    - PHP_INI_MAX_EXECUTION_TIME=300
    - PHP_INI_MAX_INPUT_VARS=4096
    - PHP_INI_MEMORY_LIMIT=512M
    - PHP_INI_DISPLAY_ERRORS=On
    - PHP_INI_DISPLAY_STARTUP_ERRORS=On
    - PHP_INI_ERROR_REPORTING=E_ALL
    - PHP_INI_EXPOSE_PHP=On
    - PHP_INI_ALLOW_URL_FOPEN=On
    - PHP_INI_OPCACHE=On
    - PHP_INI_OPCACHE_MEMORY_CONSUMPTION=2048
    - PHP_INI_APCU=On
    - PHP_INI_APD=On
    - PHP_FPM_PM=dynamic
    - PHP_FPM_PM_MAX_CHILDREN=5
    - PHP_FPM_PM_START_SERVERS=2
    - PHP_FPM_PM_MIN_SPARE_SERVERS=1
    - PHP_FPM_PM_MAX_SPARE_SERVERS=3
    - PHP_FPM_PM_PROCESS_IDLE_TIMEOUT=10s
    - PHP_FPM_PM_MAX_REQUESTS=0
    - FREETDS_1_SERVER_NAME=
    - FREETDS_1_HOST=
    - FREETDS_1_PORT=1433
    - FREETDS_1_TDS_VERSION=8.0
    - FREETDS_1_CLIENT_CHARSET=UTF-8
    - CRON=On
    - CRONTAB_1_MAILTO=
    - CRONTAB_1_EXPRESSION=
    - CRONTAB_1_COMMAND=
    - USER_ID=
    - GROUP_ID=
